# Generated by Django 4.2.9 on 2024-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
