# Generated by Django 4.2.9 on 2024-02-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_image_alt",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
