# Generated by Django 4.2.9 on 2024-01-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboraterequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
